### ISSUE TITLE
Error while trying to show server startup warnings

### ISSUE THREAD

**Issue by kimsyversen** [TylerBrock/mongo-hacker#98]
$ mongo
MongoDB shell version: 2.6.3
connecting to: test
Mongo-Hacker 0.0.4
Error while trying to show server startup warnings: not authorized on admin to execute command { getLog: "startupWarnings" }

**Comment by pathak333** [comment]
I have this error, when i try to connect with mongo shell to atlas cluster
MongoDB server version: 4.0.5
Error while trying to show server startup warnings: user is not allowed to do action [getLog] on [admin.]
MongoDB Enterprise Sandbox-shard-0:PRIMARY>

**Comment by stennie** [comment]
As of Mongo Hacker 0.0.16, `show startupWarnings` is handled by the `mongo` shell and I don't think it makes sense to override this behaviour.

Note: modern versions of the `mongo` shell will ignore some of the startup warnings that were originally reported when this issue was created in 2014 (see: [mongo/shell/utils.js](https://github.com/mongodb/mongo/blob/v4.2/src/mongo/shell/utils.js#L1001)).
